---
title: "PEEP-I Ratings Analysis"
author: "Rick O. Gilmore"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    self_contained: false
---

Analysis of emotion ratings given by participants in the PEEP-I study. 

```{r set-global-options, echo=FALSE, include=FALSE}
# Source libraries
library(ggplot2)
library(nlme)
library(knitr)
library(tidyr)
library(dplyr)

dir_data <- 'analysis/csv/'
fn_peep <- 'peep-I-ratings.csv'

# Set knitr chunk options
opts_chunk$set(comment=NA, 
               fig.width = 7, 
               fig.height = 5,
               fig.path = "figs/",
               eval = TRUE,
               warning = FALSE,
               error = FALSE,
               message = FALSE)
```

## Load data
```{r load-data}
peep.df = read.csv(paste(dir_data, fn_peep, sep=""), header=TRUE)
```

## Anger Ratings By Prosody and Script Number

```{r, anger-ratings}
a <- peep.df %>% 
  filter(rating.type == 'ang') %>%
  ggplot() +
  aes(x=ratings, fill=prosody) +
  geom_histogram() +
  facet_grid(facets = script.num ~ prosody) +
  theme(legend.position="none")
a
```

## Happy Ratings By Prosody and Script Number

```{r, happy-ratings}
h <- peep.df %>% 
  filter(rating.type == 'hap') %>%
  ggplot() +
  aes(x=ratings, fill=prosody) +
  geom_histogram() +
  facet_grid(facets = script.num ~ prosody) +
  theme(legend.position="none")
h
```